### ISSUE TITLE
Replace the attribute type by booleans

### ISSUE THREAD

**Issue by masonlouchart** [LM450N/toast-er#18]
Maybe we could replace the attribute `type` by a list of booleans to make the element more convenient to use.

**Now**

``` html
<toast-er type="info"></toast-er>
<toast-er type="error"></toast-er>
<toast-er type="warning"></toast-er>
<toast-er type="success"></toast-er>
```

**Proposal**

``` html
<toast-er info></toast-er>
<toast-er error></toast-er>
<toast-er warning></toast-er>
<toast-er success></toast-er>
```

What do you think ?

**Comment by zliebersbach** [comment]
@LM450N I could work on this.

**Comment by zliebersbach** [comment]
@LM450N In hindsight, it's probably best to keep it how it is to avoid conflicts.
e.g. If the user accidentally put on multiple attributes:

```
<toast-er info error warning></toast-er>
```

I think a string is better than booleans.

**Comment by masonlouchart** [comment]
You're right. Moreover, it will be more complicated to customize the toast type by using the object sent through the event.
