### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by masonlouchart** [LM450N/toast-er#20]
Update the dependencies versions then fix generated bugs.

**Comment by miazima** [comment]
Are you referring to bower dependencies?

**Comment by zliebersbach** [comment]
I'll gladly do this. PR on the way!

**Comment by zliebersbach** [comment]
PR #21.

**Comment by miazima** [comment]
I worked on it too! PR #22

**Comment by zliebersbach** [comment]
I fixed all breaking API changes, too, including positioning.

**Comment by masonlouchart** [comment]
Thanks to @wincinderith for its good job!
