### ISSUE TITLE
Change "middle" to "mid"

### ISSUE THREAD

**Issue by zliebersbach** [LM450N/toast-er#26]
The `heat` property should contain values as short as possible to reduce size and increase readability. So IMO, the value "middle" should be changed to "mid".

**Comment by masonlouchart** [comment]
Maybe the developer should have direct access to the speed value of the animation. I would like solve the issue #17 before doing something else.

**Comment by masonlouchart** [comment]
The element properties and methods were renamed to make the component more serious and easier to use. There is no more property `heat`. Thank you for your contribution! 👍
